spring:
  application:
    name: ecom
  datasource:
    url: "jdbc:mysql://localhost:3306/e-commerce"
    username: root
    password: 123456
  #    C?i b?n d??i ch? d?ng khi x?y s?ng v?
  #  h?c ch? th?c th? c?n t?o c?c script SQL m?i d?ng
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
    #      Hi?n  ?? debug
    show-sql: true
server:
  port: 9090
  servlet:
    context-path: /ecom
security:
  jwt:
    secret-key : 3 cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h tính b?ng mili giây
    expiration-time : 3600000

